apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: test-go3-gitops
  description: This is GitOps manifest for test-go3   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=test-go3
    backstage.io/kubernetes-id: test-go3 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: test-go3
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:test-go3
